### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by cutmaster** [numen31337/AKVideoImageView#6] opened 2017-09-17 19:38 UTC
When leaving AKVideoImageView runnin & runnin, and worse with 2 or 3 differents AKVideoImageView looping on a video, the memory used is always increasing...

**Comment by numen31337** [comment] 2017-10-12 15:16
Hey @cutmaster, looks like I can't reproduce this leak. Could you please provide me with some sample project where I can see this leak and debug it.
Here are 2 minutes of the sample project activity on my device:
![ScreenShot](https://i.imgur.com/bJOc3zq.png])

**Comment by numen31337** [comment] 2017-10-24 13:00
No feedback, closing

**Closed by numen31337** 2017-10-24 13:00 UTC
